//Root Layout : 모든 페이지에 공통적으로 적용되는 레이아웃
import type { Metadata } from "next"; //메타정보를 정의할 수 있는 타입
import { Geist, Geist_Mono } from "next/font/google"; //구글 폰트 설정
import "./globals.css"; //전역에 적용될 기본 스타일을 정의하는 css 파일
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

//폰트 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//폰트 설정
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//Next.js는 metadata 객체를 export하면, 해당 정보를 바탕으로 HTML의 <head> 태그를 자동으로 생성함
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)  
//children이라는 props는 읽기 전용이며(readonly), props의 타입은 React.ReactNode(모든 것이 가능)로 정의
{
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full xl:w-8/10 h-screen mx-auto
                        flex flex-col justify-start items-start">
          <Nav/> {/*네비게이션 컴포넌트(고정)*/}
          <main className="w-full flex-grow overflow-y-auto py-10
                           flex flex-col justify-start items-center">
            {children} {/*페이지별 컴포넌트(동적) -> Next.js 라우터가 현재 URL에 맞는 페이지 컴포넌트를 이 자리에 자동으로 삽입*/}
          </main>
          <Footer/> {/*푸터 컴포넌트(고정)*/}
        </div>
      </body>
    </html>
  );
}