//Root Layout : 모든 페이지에 공통적으로 적용되는 레이아웃
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

//font 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//폰트 설정
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//metadata 설정 -> <head> 영역에 자동으로 삽입됨
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full xl:w-8/10 h-screen mx-auto
                        flex flex-col justify-start items-start">
          {/* <Nav/> */}
          <main className="w-full flex-grow overflow-y-auto py-10
                           flex flex-col justify-start items-center">
            {children}
          </main>
          {/* <Footer/> */}
        </div>
      </body>
    </html>
  );
}
